### ISSUE TITLE
Inactive airlines have wrong colour until vimrc sourced or terminal window resized

### ISSUE THREAD

**Issue by jplrssn** [vim-airline/vim-airline-themes#107] opened 2017-09-01 21:47 UTC
Inactive airline bars (but not vertical window separators) blend into the background when creating new windows/splits. The colours are corrected by resizing the terminal window and by `:source ~/.vimrc`

Before sourcing vimrc:
![before](https://user-images.githubusercontent.com/2575219/29988781-eb77b10c-8f66-11e7-95ab-f9f2c8817a80.png)
After sourcing vimrc:
![after](https://user-images.githubusercontent.com/2575219/29988783-ed90794c-8f66-11e7-98b8-3077a72e3aac.png)

**Comment by chrisbra** [comment] 2017-10-29 08:49
looks like some colors are not correctly setup. How to reproduce?

**Comment by chrisbra** [comment] 2018-04-12 08:30
ping

**Comment by chrisbra** [comment] 2018-04-18 07:26
closing as duplicate of #58

**Closed by chrisbra** 2018-04-18 07:26 UTC
