### ISSUE TITLE
E116: Invalid arguments for function <SNR>44_airline_theme

### ISSUE THREAD

**Issue by LoLei** [vim-airline/vim-airline-themes#28] opened 2016-03-29 20:51 UTC
### Error
Getting `E116: Invalid arguments for function <SNR>44_airline_theme` when issuing the command `:AirlineTheme bubblegum` for instance. Doesn't matter what theme. The default theme does load though.

### Specs
* Arch Linux x86_64
* Kernel: 4.4.3-1-ARCH
* Vim 7.4
* vim-airline-themes 13bad30d4ee3892cae755c83433ee85fbc96d028
* vim-airline https://github.com/vim-airline/vim-airline/commit/842e5623593bc34278b8c2cf5f5a884ef581b1a0
* [Dotfiles](https://github.com/LoLei/dotfiles/tree/master/laptop)

The weird thing is, I reinstalled both gvim/vim, airline and airline-themes on both my desktop PC and my laptop which both run Arch, and this issue is only happening on my laptop...

**Comment by chrisbra** [comment] 2016-03-30 13:40
can you please poste the output of `:version?

**Comment by chrisbra** [comment] 2016-03-30 13:43
I can't reproduce with a straight 7.4 version.

**Comment by LoLei** [comment] 2016-03-30 15:59
Yes, thanks for the response.
```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 17 2016 10:50:13)
Included patches: 1-1584
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +conceal         +file_in_path    +linebreak       -mouse_sysmouse  +python3/dyn     +tcl/dyn         +wildmenu
+arabic          +cryptv          +find_in_path    +lispindent      +mouse_urxvt     +quickfix        +terminfo        +windows
+autocmd         +cscope          +float           +listcmds        +mouse_xterm     +reltime         +termresponse    +writebackup
+balloon_eval    +cursorbind      +folding         +localmap        +multi_byte      +rightleft       +textobjects     +X11
+browse          +cursorshape     -footer          +lua/dyn         +multi_lang      +ruby/dyn        +timers          -xfontset
++builtin_terms  +dialog_con_gui  +fork()          +menu            -mzscheme        +scrollbind      +title           +xim
+byte_offset     +diff            +gettext         +mksession       +netbeans_intg   +signs           +toolbar         +xsmp_interact
+channel         +digraphs        -hangul_input    +modify_fname    +packages        +smartindent     +user_commands   +xterm_clipboard
+cindent         +dnd             +iconv           +mouse           +path_extra      +startuptime     +vertsplit       -xterm_save
+clientserver    -ebcdic          +insert_expand   +mouseshape      +perl/dyn        +statusline      +virtualedit     -xpm
+clipboard       +emacs_tags      +job             +mouse_dec       +persistent_undo -sun_workshop    +visual
+cmdline_compl   +eval            +jumplist        +mouse_gpm       +postscript      +syntax          +visualextra
+cmdline_hist    +ex_extra        +keymap          -mouse_jsbterm   +printer         +tag_binary      +viminfo
+cmdline_info    +extra_search    +langmap         +mouse_netterm   +profile         +tag_old_static  +vreplace
+comments        +farsi           +libcall         +mouse_sgr       +python/dyn      -tag_any_white   +wildignore
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango
-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/lib
png16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include
/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pi
pe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/
core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1
.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX
11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-co
mmon,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -l
util -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```

**Comment by chrisbra** [comment] 2016-03-30 16:57
I believe this is a vim bug that has been fixed with a later 7.4.1600 patch. Closing as invalid.

**Comment by chrisbra** [comment] 2016-03-30 16:58
BTW: can't reproduce with 7.4.1685

**Closed by chrisbra** 2016-03-30 16:57 UTC

**Comment by LoLei** [comment] 2016-03-30 17:13
Why is it then that on my other machine I'm using vim version 7.4.1386 and I don't get the error? Maybe it's specific to 7.4.1584?

**Comment by chrisbra** [comment] 2016-03-30 17:26
some of the 7.4.1500 patches, that introduced the partial feature (don't ask me, what this is). It is supposedly be fixed by a later patch

**Comment by LoLei** [comment] 2016-03-30 17:27
Okay, well thanks for looking into it.
