### ISSUE TITLE
Tomorrow theme display is incorrect at startup

### ISSUE THREAD

**Issue by etiennebatise** [vim-airline/vim-airline-themes#39] opened 2016-05-17 19:19 UTC
Hi,

Yesterday, I did a Neobundle update of my vim and the tomorrow theme of airline became a bit incorrect. 

![screenshot_20160517_205331](https://cloud.githubusercontent.com/assets/5644956/15335692/c263c024-1c73-11e6-8bfb-4b2872aec45f.png)
![screenshot_20160517_205350](https://cloud.githubusercontent.com/assets/5644956/15335703/c4a4d4a4-1c73-11e6-8991-d04273fd9435.png)

I use Unite, and actually this weird display fixes itself when I change the colorscheme.. but only with Unite. 

What I mean is : 
1. I start vim, with Tomorrow colorscheme and tomorrow airline theme, the bug is there. 
2. I open unite and change the colorscheme to anything else, the bug goes away.
3. I go back to Tomorrow and it's all good, the bug doesn't come back. Notice that this doesn't work if do `:colorscheme whatever`

That means that the theme is correct, and I have this bug only on this one. I have tried some other ones and it's the only one with this behavior.

My vimrc is quite big with all those Unite menus conf I am using, so I doubt it would be useful.

Any idea on how to fix that ? 

Vim version 7.4.1797
Terminal : Konsole, urxvt, tmux

**Comment by chrisbra** [comment] 2016-05-17 20:40
what is your airline configuration? can you please poste the output of `:echo airline#statusline(1)`? 

Can you bisect the airline commit, that introduced this error?

**Comment by etiennebatise** [comment] 2016-05-17 22:22
The only conf I have for airline is the following:
```vimscript
let g:airline_theme='tomorrow'
let g:airline_powerline_fonts=1
let g:airline#extensions#branch#enabled = 1 
let g:airline#extensions#whitespace#enabled = 1 
let g:airline#extensions#hunks#non_zero_only = 1
```

The output of `:echo airline#statusline(1)`is:
```
%{airline#check_mode(1)}%#airline_a#%( %#airline_a_bold#%{airline#util#wrap(airline#parts#mode(),0)}%#airline_a#%{airline#util#append(airline#parts#crypt(),0)}%{airline#util#append(airline#parts#paste(),0)}%{airline#util#append(airline#par
ts#spell(),0)}%{airline#util#append("",0)}%{airline#util#append(airline#parts#iminsert(),0)} %)%#airline_a_to_airline_b#%#airline_b#%( %{airline#util#wrap(airline#extensions#hunks#get_hunks(),0)}%{airline#util#wrap(airline#extensions#bran
ch#get_head(),0)} %)%#airline_b_to_airline_c#%#airline_c#%( %<%f%m %#airline_c_red#%{airline#util#wrap(airline#parts#readonly(),0)}%#airline_c# %)%=%#airline_c_to_airline_x#%#airline_x#%( %{airline#util#wrap(airline#parts#filetype(),0)}
%)%#airline_x_to_airline_y#%#airline_y#%( %{airline#util#wrap(airline#parts#ffenc(),0)} %)%#airline_y_to_airline_z#%#airline_z#%( %3p%% %#airline_z_bold#%{g:airline_symbols.linenr}%#airline_z_bold#%4l%#airline_z#%#airline_z#%#airline_z_b
old#%#airline_z_bold#/%L%{g:airline_symbols.maxlinenr}%#airline_z#%#airline_z# :%3v %)%(%#airline_z_to_airline_warning#%#airline_warning#%( %{airline#util#wrap(airline#extensions#whitespace#check(),0)} %)%)%(%#airline_warning_to_airline_e
rror#%#airline_error#%( %{airline#util#wrap(airline#extensions#syntastic#get_warnings(),0)} %)%)
```

I have tryied bisecting the commit but I haven't found yet. Something new : the bug goes away if I `:so ~/.vimrc`

**Comment by iovis9** [comment] 2016-08-15 11:38
I'm having a similar problem. With Tomorrow theme (probably irrelevant) it doesn't change colors for modified buffers. It solves itself by manually calling `:AirlineTheme tomorrow` and sometimes by resourcing `.vimrc`.

Options:
```
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'tomorrow'
```

The output of `:echo airline#statusline(1)` is:

`%{airline#check_mode(1)}%#airline_a#%( %#airline_a_bold#%{airline#util#wrap(airline#parts#mode(),0)}%#airline_a#%{airline#util#
append(airline#parts#crypt(),0)}%{airline#util#append(airline#parts#paste(),0)}%{airline#util#append(airline#parts#spell(),0)}%
{airline#util#append("",0)}%{airline#util#append(airline#parts#iminsert(),0)} %)%#airline_a_to_airline_b#%#airline_b#%( %{airl
ine#util#wrap(airline#extensions#hunks#get_hunks(),0)}%{airline#util#wrap(airline#extensions#branch#get_head(),0)} %)%#airline_
b_to_airline_c#%#airline_c#%( %<%f%m %#airline_c_red#%{airline#util#wrap(airline#parts#readonly(),0)}%#airline_c# %)%=%#airlin
e_c_to_airline_x#%#airline_x#%( %{airline#util#wrap(airline#parts#filetype(),0)} %)%#airline_x_to_airline_y#%#airline_y#%( %{
airline#util#wrap(airline#parts#ffenc(),0)} %)%#airline_y_to_airline_z#%#airline_z#%( %3p%% %#airline_z_bold#%{g:airline_symbo
ls.linenr}%#airline_z_bold#%4l%#airline_z#%#airline_z#%#airline_z_bold#%#airline_z_bold#/%L%{g:airline_symbols.maxlinenr}%#airl
ine_z#%#airline_z# :%3v %)%(%#airline_z_to_airline_warning#%#airline_warning#%( %{airline#util#wrap(airline#extensions#whitesp
ace#check(),0)} %)%)`

**Comment by chrisbra** [comment] 2017-01-19 08:08
duplicate of #58

**Closed by chrisbra** 2017-01-19 08:08 UTC
