### ISSUE TITLE
Base 16: Light theme variants.

### ISSUE THREAD

**Issue by ghost** [vim-airline/vim-airline-themes#79] opened 2017-03-17 01:06 UTC
'base16-summerfruit' and 'base16-tomorrow' match with the dark colour schemes. I think it would be great if the light themes were also supported.

**Comment by chrisbra** [comment] 2017-03-17 13:49
duplicate of #5 
someone has to actually create light versions, but I can't do it. So go ahead and create them.

**Closed** 2017-04-30 17:13 UTC
