### ISSUE TITLE
Base 16 themes doesn't consider dark background

### ISSUE THREAD

**Issue by nathanajah** [vim-airline/vim-airline-themes#33] opened 2016-04-08 05:26 UTC
Most base16 themes have both dark and light variations. However, the base16 themes here does not seem to have a dark version.

Is there any plan to fix this?

Currently, I'm just using the base16 theme, since the base16_ocean theme does not have a dark theme.

**Comment by chrisbra** [comment] 2016-04-08 06:41
duplicate of #5 
Those base16 themes were generated and did not distinguish light and dark settings. If anybody wants to work on that, I am open for PR. But I am not good at colorschemes.

**Closed by chrisbra** 2016-04-08 06:41 UTC
