### ISSUE TITLE
release version

### ISSUE THREAD

**Issue by shibumi** [vim-airline/vim-airline-themes#75] opened 2017-03-01 22:49 UTC
Hello,
Could you please provide a github release version? It would be much easier to package. Thank you :)

**Comment by chrisbra** [comment] 2017-03-02 07:14
sure. what are you packaging for?

**Comment by shibumi** [comment] 2017-03-02 19:11
@chrisbra 
Arch Linux

**Comment by highvoltage** [comment] 2018-04-05 12:47
Hi, I've also packaged it for Debian but it's currently version 0 with a git commit attached as the version, would really be nice if there was a release.

**Comment by shibumi** [comment] 2018-04-05 17:26
@chrisbra  why did you close this issue?

**Comment by chrisbra** [comment] 2018-04-05 21:14
It is not closed. In any case, I don't think tagging here is necessary. Just make a snapshot and distribute it.

**Comment by chrisbra** [comment] 2018-04-09 12:46
I cannot guarantee anything and even if I did, what do you take of the word from a total stranger on the Internet? :) However, since we are only talking about  themes here, it is unlikely that it will break something serious. In the worst case once needs to use a different theme temporarily until the issue is closed (meaning somebody taken the time to fix whatever is broken). Obviously many changes only affect the visual representation and what is onced changed bothers somebody else (see e.g. #131).

Note, I cannot test every scheme distributed here whether it looks like intended (and even then would it have to be verified in different terminals, guis with and without 'termguicolors' setting and  with different 't_Co' settings). So I am very much dependent on the issues and PR submitted here when I make changes. That is also the reason why several issues are open here. I simply cannot reproduce (and therefore fix) those issues.

**Comment by chrisbra** [comment] 2018-04-18 07:26
closing

**Closed by chrisbra** 2018-04-18 07:26 UTC
