### ISSUE TITLE
Change theme but nothing happen

### ISSUE THREAD

**Issue by hong-duc** [vim-airline/vim-airline-themes#104] opened 2017-08-24 14:30 UTC
I try to change theme with this command `AirlineTheme base16_3024` but nothing happen.
It just stay like this
![menu_021](https://user-images.githubusercontent.com/12032550/29671190-10b3cb0e-8913-11e7-95f6-eb092d75ee0c.png)

My .vimrc
```
set nocompatible
filetype plugin indent on
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'leafgarland/typescript-vim'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Initialize plugin system
call plug#end()

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
autocmd BufEnter * silent! lcd %:p:h
```

**Comment by chrisbra** [comment] 2017-08-24 14:35
possible duplicate of #65
(please go throught some of the hints mentioned there to find out what is going on)

**Closed** 2017-10-29 08:49 UTC
