### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by herohamp** [vim-airline/vim-airline-themes#85] opened 2017-04-26 21:00 UTC
```
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Bundle 'Lokaltog/vim-easymotion'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()            " required


syntax on

Bundle 'nerdtree'

colorscheme atom-dark
set mouse=a
set number

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

map <C-n> :NERDTreeToggle<CR>
```

and when I run :AirlineTheme simple nothing changes?

**Comment by chrisbra** [comment] 2017-04-30 17:12
duplicate of #65?

**Closed** 2017-05-14 15:01 UTC
